### ISSUE TITLE
ScaleSetTemplate conflict

### ISSUE THREAD

**Issue by FedericoPalma92** [pateixei/MoodleAzure#3]
Hi, 

I'm trying to deploy your template in azure but the deploy fail on the resource "ScaleSetTemplate" with the following error: 

{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningError",
        "message": "VM has reported a failure when processing extension 'setup_moodle'. Error message: \"Command returned an error.\n---stdout---\n\n---errout---\ndpkg-preconfigure: unable to re-open stdin: No such file or directory\ngpg: keyring `/tmp/tmpvdygynm1/secring.gpg' created\ngpg: keyring `/tmp/tmpvdygynm1/pubring.gpg' created\ngpg: requesting key 3FE869A9 from hkp server keyserver.ubuntu.com\ngpg: /tmp/tmpvdygynm1/trustdb.gpg: trustdb created\ngpg: key 3FE869A9: public key \"Launchpad PPA for Gluster\" imported\ngpg: Total number processed: 1\ngpg:               imported: 1  (RSA: 1)\ndpkg-preconfigure: unable to re-open stdin: No such file or directory\ngpg: keyring `/tmp/tmp6fld5em1/secring.gpg' created\ngpg: keyring `/tmp/tmp6fld5em1/pubring.gpg' created\ngpg: requesting key E5267A6C from hkp server keyserver.ubuntu.com\ngpg: /tmp/tmp6fld5em1/trustdb.gpg: trustdb created\ngpg: key E5267A6C: public key \"Launchpad PPA for Ond\\xc5\\x99ej Sur\" imported\ngpg: Total number processed: 1\ngpg:               imported: 1  (RSA: 1)\nException in thread Thread-1:\nTraceback (most recent call last):\n  File \"/usr/lib/python3.4/threading.py\", line 920, in _bootstrap_inner\n    self.run()\n  File \"/usr/lib/python3.4/threading.py\", line 868, in run\n    self._target(*self._args, **self._kwargs)\n  File \"/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py\", line 687, in addkey_func\n    func(**kwargs)\n  File \"/usr/lib/python3/dist-packages/softwareproperties/ppa.py\", line 370, in add_key\n    return apsk.add_ppa_signing_key()\n  File \"/usr/lib/python3/dist-packages/softwareproperties/ppa.py\", line 261, in add_ppa_signing_key\n    tmp_export_keyring, signing_key_fingerprint, tmp_keyring_dir):\n  File \"/usr/lib/python3/dist-packages/softwareproperties/ppa.py\", line 210, in _verify_fingerprint\n    got_fingerprints = self._get_fingerprints(keyring, keyring_dir)\n  File \"/usr/lib/python3/dist-packages/softwareproperties/ppa.py\", line 202, in _get_fingerprints\n    output = subprocess.check_output(cmd, universal_newlines=True)\n  File \"/usr/lib/python3.4/subprocess.py\", line 609, in check_output\n    output, unused_err = process.communicate(inputdata, timeout=timeout)\n  File \"/usr/lib/python3.4/subprocess.py\", line 947, in communicate\n    stdout = _eintr_retry_call(self.stdout.read)\n  File \"/usr/lib/python3.4/subprocess.py\", line 491, in _eintr_retry_call\n    return func(*args)\n  File \"/usr/lib/python3.4/encodings/ascii.py\", line 26, in decode\n    return codecs.ascii_decode(input, self.errors)[0]\nUnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 92: ordinal not in range(128)\n\nW: GPG error: http://ppa.launchpad.net trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4F4EA0AAE5267A6C\nE: There are problems and -y was used without --force-yes\nE: There are problems and -y was used without --force-yes\nMount failed. Please check the log file for more details.\ncp: cannot stat '/etc/apache2/apache2.conf': No such file or directory\nsed: can't read /etc/apache2/apache2.conf: No such file or directory\nsetup_moodle.sh: line 66: /etc/apache2/apache2.conf: No such file or directory\nsudo: a2enmod: command not found\nsetup_moodle.sh: line 72: /etc/apache2/sites-enabled/000-default.conf: No such file or directory\nsed: can't read /etc/php/5/apache2/php.ini: No such file or directory\nsed: can't read /etc/php/5/apache2/php.ini: No such file or directory\nsed: can't read /etc/php/5/apache2/php.ini: No such file or directory\nsed: can't read /etc/php/5/apache2/php.ini: No such file or directory\nsed: can't read /etc/php/5/apache2/php.ini: No such file or directory\nsed: can't read /etc/php/5/apache2/php.ini: No such file or directory\nsed: can't read /etc/php/5/apache2/php.ini: No such file or directory\nsed: can't read /etc/php/5/apache2/php.ini: No such file or directory\napache2: unrecognized service\n\n\"."
      }
    ]
  }
}

Can you  help me please ?

**Comment by pateixei-zz** [comment]
Hi, 

I'm doing some architectural changes and the template is broken for a while, probably during this entire week. 
If it's urgent for you to deploy an environment, I recommend you using the V1 branch instead, it should work with no issues. 

HTH

**Comment by pateixei-zz** [comment]
As soon I've the template fixed, I'll close this issue, ok?

**Comment by FedericoPalma92** [comment]
ok thank you.

I have another question, i need to do some stress test with jmeter. I have insert a new vm with jmeter in the resource group and configured jmeter but when i'm going to call the site via ip the browser responds with the following error: "ERR_CONNECTION_REFUSED". can you guide me to enable connetion via ip ?

**Comment by pateixei-zz** [comment]
template updated.
